title: "Venkatesh Gella"
logo:asset/Venkatesh.jpg
description: "PYTHON | DOORS NEXT GENERATION |MATLAB Simulink | Automation | Automotive | V&V | AGILE |JIRA | DOORS | dSpace | HIL Testing | BCM | OBD II | CAN | LIN | HVAC | PLANT MODELS | Control Desk | Trace32| JAVA SCRIPT"
theme: minima
